name = "CircleFinding"
uuid = "ffb31868-da07-46aa-8300-369b7f0e1b29"
authors = ["Joey Nelson <joey@joescan.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
